const CREATE = {
  REQUEST: '@service/CREATE_REQUEST',
  SUCCESS: '@service/CREATE_SUCCESS',
};

const ADD_PROBLEM = {
  REQUEST: '@service/ADD_PROBLEM_REQUEST',
  SUCCESS: '@service/ADD_PROBLEM_SUCCESS',
};

const ADD_PROCEDURE = {
  REQUEST: '@service/ADD_PROCEDURE_REQUEST',
  SUCCESS: '@service/ADD_PROCEDURE_SUCCESS',
};

export { CREATE, ADD_PROBLEM, ADD_PROCEDURE };
