const CREATE = {
  REQUEST: '@service/CREATE_REQUEST',
  SUCCESS: '@service/CREATE_SUCCESS',
};

const ADD_PROBLEM = {
  REQUEST: '@service/ADD_PROBLEM_REQUEST',
  SUCCESS: '@service/ADD_PROBLEM_SUCCESS',
};

const ADD_PROCEDURE = {
  REQUEST: '@service/ADD_PROCEDURE_REQUEST',
  SUCCESS: '@service/ADD_PROCEDURE_SUCCESS',
};

const REMOVE_PROCEDURE = {
  REQUEST: '@service/REMOVE_PROCEDURE_REQUEST',
  SUCCESS: '@service/REMOVE_PROCEDURE_SUCCESS',
};

const FINISH = {
  REQUEST: '@service/FINISH_REQUEST',
  SUCCESS: '@service/FINISH_SUCCESS',
};

export { CREATE, ADD_PROBLEM, ADD_PROCEDURE, REMOVE_PROCEDURE, FINISH };
